name: verify

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install --global npm@10.9.4
      - run: npm --version
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run: npm run verify
